// Generated by CoffeeScript 1.9.2
(function() {
  var DbHelper, Users, app, bodyParser, cookieParser, database, email, express, favicon, logger, path, routes, users;

  express = require('express');

  path = require('path');

  favicon = require('serve-favicon');

  logger = require('morgan');

  cookieParser = require('cookie-parser');

  bodyParser = require('body-parser');

  routes = require('./routes/index');

  Users = require('./routes/users');

  email = require('./routes/email');

  DbHelper = require('./routes/db-helper');

  app = express();

  database = new DbHelper('mongodb://localhost:27017/nodetest2');

  users = new Users(database);

  app.set('views', path.join(__dirname, 'views'));

  app.set('view engine', 'jade');

  app.use(logger('dev'));

  app.use(bodyParser.json());

  app.use(bodyParser.urlencoded({
    extended: false
  }));

  app.use(cookieParser());

  app.use(express["static"](path.join(__dirname, 'public')));

  app.get('/userlist', users.list);

  app.post('/adduser', users.postUser);

  app.use('/', routes);

  app.use('/email', email);

  module.exports = app;

}).call(this);
