// Generated by CoffeeScript 1.9.2
(function() {
  var api_key, domain, express, mailgun, router;

  express = require('express');

  router = express.Router();

  api_key = '{API KEY}';

  domain = '{DOMAIN}';

  mailgun = require('mailgun-js')({
    apiKey: api_key,
    domain: domain
  });

  router.post('/sendemail', function(req, res) {
    req.body.from = '{FROM}';
    mailgun.messages().send(req.body, function(error, body) {
      res.send(body.message ? {
        msg: body.message
      } : error);
      console.log(body);
    });
  });

  module.exports = router;

}).call(this);
