// Generated by CoffeeScript 1.9.2
(function() {
  var api_key, domain, express, mailgun, router;

  express = require('express');

  router = express.Router();

  api_key = 'key-ba206f91379f71160f6dbd943df6c8a9';

  domain = 'sandboxdba4f7a1e909423499712ca23de2fb01.mailgun.org';

  mailgun = require('mailgun-js')({
    apiKey: api_key,
    domain: domain
  });

  router.post('/sendemail', function(req, res) {
    req.body.from = 'Test <mailgun@sandboxdba4f7a1e909423499712ca23de2fb01.mailgun.org>';
    mailgun.messages().send(req.body, function(error, body) {
      res.send(body.message ? {
        msg: body.message
      } : error);
      console.log(body);
    });
  });

  module.exports = router;

}).call(this);
