// Generated by CoffeeScript 1.9.2
(function() {
  var api_key, domain, express, mailgun, router, twilio, twilio_accountSid, twilio_authToken;

  express = require('express');

  router = express.Router();

  api_key = '{API KEY}';

  domain = '{DOMAIN}';

  mailgun = require('mailgun-js')({
    apiKey: api_key,
    domain: domain
  });

  twilio_accountSid = '{TWILIO ACCOUNT SID}';

  twilio_authToken = '{TWILIO AUTHTOKEN}';

  twilio = require('twilio')(twilio_accountSid, twilio_authToken);


  /*
  * POST to sendemail
   */

  router.post('/sendemail', function(req, res) {
    req.body.from = '{FROM}';
    mailgun.messages().send(req.body, function(error, body) {
      res.send(body.message != null ? {
        msg: body.message
      } : error);
      console.log(body);
    });
  });


  /*
  * POST to sendsms
   */

  router.post('/sendsms', function(req, res) {
    req.body.from = '{FROM NUMBER}';
    twilio.messages.create(req.body, function(error, body) {
      if (body != null) {
        res.send({
          'status': 'OK'
        });
      } else {
        res.send({
          'status': 'ERROR'
        });
        console.log(error);
      }
    });
  });

  module.exports = router;

}).call(this);
