express = require('express')

class Constants
    @local:
        MAILGUN_API_KEY : '{MAILGUN_API_KEY}'
        MAILGUN_DOMAIN : '{MAILGUN_DOMAIN}'
        TWILIO_ACCOUNTSID : '{TWILIO_ACCOUNTSID}'
        TWILIO_AUTHTOKEN : '{TWILIO_AUTHTOKEN}'
        NOTIFICATIONS_DUPLICATES_THRESHOLD_SEC : 300

    @prod:
        MAILGUN_API_KEY : '{MAILGUN_API_KEY}'
        MAILGUN_DOMAIN : '{MAILGUN_DOMAIN}'
        TWILIO_ACCOUNTSID : '{TWILIO_ACCOUNTSID}'
        TWILIO_AUTHTOKEN : '{TWILIO_AUTHTOKEN}'
        NOTIFICATIONS_DUPLICATES_THRESHOLD_SEC : 300

module.exports = Constants
