// Generated by CoffeeScript 1.9.2
(function() {
  var Constants, express;

  express = require('express');

  Constants = (function() {
    function Constants() {}

    Constants.local = {
      MAILGUN_API_KEY: '{MAILGUN_API_KEY}',
      MAILGUN_DOMAIN: '{MAILGUN_DOMAIN}',
      TWILIO_ACCOUNTSID: '{TWILIO_ACCOUNTSID}',
      TWILIO_AUTHTOKEN: '{TWILIO_AUTHTOKEN}',
      NOTIFICATIONS_DUPLICATES_THRESHOLD_SEC: 300
    };

    Constants.prod = {
      MAILGUN_API_KEY: '{MAILGUN_API_KEY}',
      MAILGUN_DOMAIN: '{MAILGUN_DOMAIN}',
      TWILIO_ACCOUNTSID: '{TWILIO_ACCOUNTSID}',
      TWILIO_AUTHTOKEN: '{TWILIO_AUTHTOKEN}',
      NOTIFICATIONS_DUPLICATES_THRESHOLD_SEC: 300
    };

    return Constants;

  })();

  module.exports = Constants;

}).call(this);
